### PR TITLE
Add ICDAR 2017 KWS Evaluation tool

### PR DESCRIPTION
**Pull request by jpuigcerver**
Hi Giorgios,

I added the evaluation function for the ICDAR 2017 KWS Competition. Just a few clarifications when you add the competition benchmarks:

Both tracks (QbE and QbS) use the same evaluation function: icdar2017_kws_tool

The difference is the arguments that they use.

For QbS, you have to pass the options:
privatedata = competitions/executables/Icdar17KwsEval/Eval_QbS_GT.txt
querylist = competitions/executables/Icdar17KwsEval/Eval_Query_Keywords.txt

For QbE, you have to pass the options:
privatedata = competitions/executables/Icdar17KwsEval/Eval_QbE_GT.txt
querygroups = competitions/executables/Icdar17KwsEval/Eval_Query_Images.txt

These files ARE NOT included in the pull requests, since they cannot be made public yet. I'll send you them privately.

### CODE REVIEW

**Comment by sfikas** [comment]
Joan, there's no point sending the private files to me. You should upload them yourself, using the django admin interface (competition->track->subtrack->upload private data).

Also, please make sure that the whole pipeline works on your own machine (ie, run django locally) before asking to integrate the code on the production server.

**Comment by jpuigcerver** [comment]
Hi,

I am not an admin of the competition in the production site.

**Comment by jpuigcerver** [comment]
Hi again, Georgios.

I modified the evaluation function to use a tar.gz as the private data and have the competition running in my local machine. Let me know how to integrate this into the actual competition site.

**Comment by sfikas** [comment]
Done -- I merged the PR to the develop branch, and to the production server branch.
Just add the private data and "evaluator" and "benchmark" objects on the django admin, like you did on your local machine, and it should be ok.

**Comment by jpuigcerver** [comment]
Done! Thanks for your help.

**Pull request merged**
